import { NextResponse } from "next/server";
import { eq } from "drizzle-orm";
import { db } from "@/lib/db";
import { proposals, events } from "@/lib/db/schema";
import { generateProposalDocument, DocumentGenerationError } from "@/lib/document-service";
import { getCurrentUser } from "@/lib/auth";
import { notifyDiscord } from "@/lib/discord";

export const dynamic = "force-dynamic";

// POST /api/proposals/:id/documents — generate a PDF from the proposal's
// current section content (architecture.md 3.6). Usable any time every
// section has content (not gated to "approved") so a salesperson can see
// what the final document will look like before submitting for review.
export async function POST(
  _request: Request,
  { params }: { params: Promise<{ id: string }> }
) {
  const { id } = await params;
  const user = await getCurrentUser();
  if (!user) return NextResponse.json({ error: "Not signed in" }, { status: 401 });

  const proposal = await db.query.proposals.findFirst({ where: eq(proposals.id, id) });
  if (!proposal) return NextResponse.json({ error: "Proposal not found" }, { status: 404 });

  try {
    const doc = await generateProposalDocument(id);
    await db.insert(events).values({
      proposalId: id,
      eventType: "document_generated",
      detail: `PDF generated by ${user.name}`,
    });
    // A successful generation here is the only way out of a prior
    // document_failed state (retried from the same "Send to client" button
    // used for send_failed — see canSend in ProposalEditor), so clear it
    // back to approved rather than leaving the proposal stuck.
    if (proposal.status === "document_failed") {
      await db
        .update(proposals)
        .set({ status: "approved", lastError: null, updatedAt: new Date() })
        .where(eq(proposals.id, id));
    }
    return NextResponse.json({ ok: true, documentId: doc.id }, { status: 201 });
  } catch (err) {
    const reason = err instanceof Error ? err.message : String(err);

    if (err instanceof DocumentGenerationError) {
      // Sections not yet complete — a normal, correctable validation state
      // (the UI already disables this action until every section has
      // content), not a system failure. Don't log it as a document_failed
      // event or touch proposal status.
      return NextResponse.json({ error: "Document generation failed", detail: reason }, { status: 400 });
    }

    await db.insert(events).values({
      proposalId: id,
      eventType: "document_failed",
      detail: reason,
    });

    // Only move the whole proposal into document_failed (which the
    // dashboard and canSend both treat as "was approved and on its way to
    // the client") when that's actually true — i.e. it was already
    // approved, or already in one of these failed states. A render failure
    // while just previewing an unapproved draft is still a real failure
    // worth logging above, but must not lock an unapproved proposal out of
    // normal editing/submission by implying it was ever headed to send.
    if (
      proposal.status === "approved" ||
      proposal.status === "document_failed" ||
      proposal.status === "send_failed"
    ) {
      await db
        .update(proposals)
        .set({ status: "document_failed", lastError: reason, updatedAt: new Date() })
        .where(eq(proposals.id, id));

      await notifyDiscord({
        kind: "document_failed",
        proposalId: id,
        clientName: proposal.clientName,
        companyName: proposal.companyName,
        detail: reason,
      });
    }
    return NextResponse.json({ error: "Document generation failed", detail: reason }, { status: 502 });
  }
}
