import { NextResponse } from "next/server";
import { eq } from "drizzle-orm";
import { db } from "@/lib/db";
import { proposals, sections, sectionVersions, events, attachments } from "@/lib/db/schema";
import { contentNeedsInput, isEditableStatus, SectionKey } from "@/lib/proposal-fields";
import { regenerateProposalSection, GenerationError } from "@/lib/anthropic";
import { getCurrentUser } from "@/lib/auth";
import { trackOwnershipPickup } from "@/lib/ownership";

export const dynamic = "force-dynamic";

// POST /api/proposals/:id/sections/:sectionId/regenerate — regenerate a
// single section, passing the other current sections as fixed context so
// tone/facts stay consistent, and leaving every other section's content and
// version history completely untouched (PRD scenario 4).
//
// Gated to the same statuses as a manual edit (see the PATCH route on this
// same resource) — regenerating after approval is just as capable of
// reintroducing a "[NEEDS INPUT: ...]" placeholder into an otherwise-final
// proposal as a manual edit is, so it needs the same server-side guard.
export async function POST(
  request: Request,
  { params }: { params: Promise<{ id: string; sectionId: string }> }
) {
  const { id, sectionId } = await params;
  const user = await getCurrentUser();
  if (!user) return NextResponse.json({ error: "Not signed in" }, { status: 401 });

  const body = await request.json().catch(() => ({}) as { reviewerNote?: string });

  const proposal = await db.query.proposals.findFirst({
    where: eq(proposals.id, id),
    with: { intakeFields: true, sections: true },
  });
  const targetSection = await db.query.sections.findFirst({
    where: eq(sections.id, sectionId),
  });

  if (!proposal || !targetSection || targetSection.proposalId !== id) {
    return NextResponse.json({ error: "Section not found" }, { status: 404 });
  }
  if (!isEditableStatus(proposal.status)) {
    return NextResponse.json(
      { error: `Cannot regenerate a section while status is "${proposal.status}"` },
      { status: 409 }
    );
  }

  const materials = await db
    .select()
    .from(attachments)
    .where(eq(attachments.proposalId, id));

  const intake = Object.fromEntries(
    proposal.intakeFields.map((f) => [f.fieldKey, f.fieldValue])
  );
  const otherSections = Object.fromEntries(
    proposal.sections
      .filter((s) => s.id !== sectionId)
      .map((s) => [s.sectionKey, s.currentContent])
  ) as Partial<Record<SectionKey, string>>;

  try {
    const content = await regenerateProposalSection({
      sectionKey: targetSection.sectionKey,
      intake,
      otherSections,
      supportingMaterial: materials
        .filter((m) => m.extractedText)
        .map((m) => ({ filename: m.filename, extractedText: m.extractedText! })),
      reviewerNote: body?.reviewerNote,
    });
    const needsInput = contentNeedsInput(content);

    const [version] = await db
      .insert(sectionVersions)
      .values({ sectionId, content, generatedBy: "ai", needsInput })
      .returning();
    await db
      .update(sections)
      .set({
        currentContent: content,
        needsInput,
        currentVersionId: version.id,
        updatedAt: new Date(),
      })
      .where(eq(sections.id, sectionId));

    await db.insert(events).values({
      proposalId: id,
      eventType: "section_regenerated",
      detail: `${targetSection.sectionKey} regenerated by ${user.name}`,
    });

    await trackOwnershipPickup({
      proposal,
      actingUser: user,
      actionLabel: `regenerated ${targetSection.sectionKey}`,
    });

    return NextResponse.json({ ok: true, content, needsInput });
  } catch (err) {
    const reason =
      err instanceof GenerationError ? `${err.kind}: ${err.message}` : String(err);
    await db.insert(events).values({
      proposalId: id,
      eventType: "generation_failed",
      detail: `regenerate ${targetSection.sectionKey}: ${reason}`,
    });
    return NextResponse.json({ error: "Regeneration failed", detail: reason }, { status: 502 });
  }
}
