import { put } from "@vercel/blob";

// Document storage, backed by Vercel Blob. This used to be a local-disk
// implementation (see git history / README), which worked for `next dev`
// but broke in two ways once this actually deployed to Vercel: (1) each
// serverless invocation gets its own ephemeral filesystem, so a PDF
// generated by one invocation was routinely gone by the time a later
// invocation tried to serve its download link, and (2) `readFile()` on a
// fully dynamic, database-sourced path (see the download route) can't be
// statically scoped to a subfolder, so Next's build-time file tracer
// couldn't prove which files it needed and fell back to bundling the
// entire project into the server output — the "whole project traced"
// build error this replaced.
//
// Requires a `BLOB_READ_WRITE_TOKEN` env var — Vercel adds this
// automatically to the project once a Blob store is connected
// (Project → Storage → Create Database → Blob), and the same token works
// for local dev (`vercel env pull`, or copy it into `.env` by hand).
//
// Nothing outside this file changes: callers still only see `storagePath`
// as an opaque string — it's a Blob URL now instead of a local path, but
// the contract (save returns a string, read takes that string back) is
// identical.

function contentTypeFor(extension: string): string {
  if (extension === "pdf") return "application/pdf";
  if (extension === "html") return "text/html; charset=utf-8";
  return "application/octet-stream";
}

export async function saveDocumentFile(
  proposalId: string,
  documentId: string,
  buffer: Buffer,
  extension: string
): Promise<string> {
  const blob = await put(`documents/${proposalId}/${documentId}.${extension}`, buffer, {
    access: "public",
    addRandomSuffix: false,
    contentType: contentTypeFor(extension),
  });
  return blob.url;
}

export async function readDocumentFile(storagePath: string): Promise<Buffer> {
  const res = await fetch(storagePath);
  if (!res.ok) {
    throw new Error(`Could not fetch stored document (${res.status}): ${storagePath}`);
  }
  return Buffer.from(await res.arrayBuffer());
}
