import { put } from "@vercel/blob";
import { mkdir, readFile, writeFile } from "fs/promises";
import path from "path";

// Document storage, with two backends switched at build time on NODE_ENV:
//
// - `next dev` (NODE_ENV === "development"): local disk, under
//   ./storage/documents. Simple, no external dependency, nothing to set up.
// - Everything else — a real `next build` (Vercel prod/preview, or
//   `next build && next start` locally) — Vercel Blob.
//
// This isn't a runtime toggle (e.g. checking `process.env.VERCEL`): Next
// statically replaces `process.env.NODE_ENV` at build time and then
// dead-code-eliminates the unreachable branch, so the local-disk branch's
// `fs` calls are compiled out of a production build entirely — they never
// reach Next's build-time file tracer. That matters because they used to
// break the actual build: `readDocumentFile`'s path comes straight from the
// database (see the download route), so it's fully dynamic with nothing
// for the tracer to statically scope to a subfolder, and its fallback for
// "can't prove which files this needs" is to bundle the entire project into
// the server output — the "whole project traced" build error this avoids.
// (This is the same escape hatch Next's own warning for this suggests:
// "only use [dynamic filesystem paths] in development.") A runtime check
// would leave that same fs call sitting in the production bundle for the
// tracer to trip over regardless of which branch actually runs — the
// NODE_ENV check has to be literally what gates it, not some indirection
// derived from it, or the dead-code elimination won't fire.
//
// Local disk also just doesn't work in production regardless of the build
// error: a serverless function's filesystem is ephemeral and isn't shared
// across invocations, so a PDF generated by one invocation can be gone by
// the time a later invocation serves its download link. Fine for a single
// long-running `next dev` process; not fine deployed.
//
// Nothing outside this file changes either way — callers only ever see
// `storagePath` as an opaque string, whether it's a local path or a Blob
// URL. Requires `BLOB_READ_WRITE_TOKEN` in any non-dev environment (Vercel
// adds it automatically once a Blob store is connected: Project → Storage →
// Create Database → Blob); not needed for local dev at all now.

const STORAGE_ROOT = path.join(process.cwd(), "storage", "documents");

function contentTypeFor(extension: string): string {
  if (extension === "pdf") return "application/pdf";
  if (extension === "html") return "text/html; charset=utf-8";
  return "application/octet-stream";
}

export async function saveDocumentFile(
  proposalId: string,
  documentId: string,
  buffer: Buffer,
  extension: string
): Promise<string> {
  if (process.env.NODE_ENV === "development") {
    const dir = path.join(STORAGE_ROOT, proposalId);
    await mkdir(dir, { recursive: true });
    const filePath = path.join(dir, `${documentId}.${extension}`);
    await writeFile(filePath, buffer);
    return filePath;
  }

  const blob = await put(`documents/${proposalId}/${documentId}.${extension}`, buffer, {
    access: "public",
    addRandomSuffix: false,
    contentType: contentTypeFor(extension),
  });
  return blob.url;
}

export async function readDocumentFile(storagePath: string): Promise<Buffer> {
  if (process.env.NODE_ENV === "development") {
    return readFile(storagePath);
  }

  const res = await fetch(storagePath);
  if (!res.ok) {
    throw new Error(`Could not fetch stored document (${res.status}): ${storagePath}`);
  }
  return Buffer.from(await res.arrayBuffer());
}
